# Server Port (to avoid 8080 conflict)
server.port=8085

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/workshop_db
spring.datasource.username=root
spring.datasource.password=Aasin@80235

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect